trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: npm ci
    displayName: "setup"

  - script: npm run test
    displayName: "test"

  - script: npm run build
    displayName: "build"

  - script: npm prune --omit=dev
    displayName: "npm prune"

  - script: zip -r --symlinks '$(Build.ArtifactStagingDirectory)/nose.zip' .
    displayName: archive, add dist
    workingDirectory: "dist"

  - script: zip -r --symlinks '$(Build.ArtifactStagingDirectory)/nose.zip' node_modules
    displayName: archive add node_modules
    workingDirectory: "."

  - task: PublishBuildArtifacts@1
    displayName: publish
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/nose.zip"
      ArtifactName: "nose"
      publishLocation: "Container"
