trigger:
  branches:
    exclude:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: npm ci
    displayName: "setup"

  - script: |
      npm run check-format || exit 1;
      npm run check-lint || exit 1;
    displayName: "validate code style"

  - script: npm run build
    displayName: "validate build"

  - script: npm run test
    displayName: "run tests"
